### ISSUE TITLE
Understanding the equation

### ISSUE THREAD

**Issue by souvikita** [HinodeXRT/xrtpy#296]
https://github.com/HinodeXRT/xrtpy/blob/87ae6f8203a9da827cb70463f5a7fbb22599a3db/xrtpy/response/temperature_from_filter_ratio.py#L464

Can you please explain this equation? I do not directly understand why this multiplication with a and b is done and then divided by the sum of a and b. Would appreciate any help in this regard.

**Comment by joyvelasquez** [comment]
@souvikita Thank you for raising this question!

This is performing linear interpolation between two adjacent temperature values in the `Tmodel`, based on how close the observed filter ratio (`data_ratio`) is to the model ratios (`model_ratio').

- `a` and `b` represent the differences between the observed filter ratio and the model ratios for the two adjacent temperature points in Tmodel.

- The formula is designed to weigh these two temperatures proportionally, with more weight given to the temperature whose model ratio is closer to the observed filter ratio

In essence, this allows for a smooth transition between temperature values, rather than jumping from one discrete temperature to another. Hi @jslavin , can you verify on this statement about the equation mentioned by Souvik.

Let me know if you need further clarification!

**Comment by joyvelasquez** [comment]
@jslavin Perhaps we should add a comment on this equation in the script?

**Comment by jslavin** [comment]
Yes, you've done a good job of explaining what the equation does. As you say, it's linearly interpolating between adjacent values on the filter_ratio, temperature grid to get the temperature given a filter_ratio.
I'm open to adding a comment to the code saying that.

**Comment by joyvelasquez** [comment]
Hi @souvikita, just checking in to see if the explanation was clear or if need more information ?
