### ISSUE TITLE
Improve error message for dates chosen after end of contamination data

### ISSUE THREAD

**Issue by namurphy** [HinodeXRT/xrtpy#81]
The bug raised in #74 occurred because a date was chosen after the end of the contamination data file.  It would be helpful to have an error message for when a user picks a date that is after the end of the data contained in the contamination data file, like "No contamination data is presently available for <date>."  This could be done in a `try`/`except` block.

**Comment by wtbarnes** [comment]
As someone who just hit the bug referenced above, I definitely agree. It wasn't immediately obvious to me that this is what the issue was or if I had just input the date incorrectly.

I wonder too if it would be possible to (maybe optionally) interpolate the last available contamination value to the current date if it is outside the range and issue a warning letting the user know this is what is happening. I would imagine this is likely a better estimate than being forced to not include any contamination at those dates.

**Comment by joyvelasquez** [comment]
Close by #86
